export { default as contactIcon } from "./images/contactIcon.svg";
export { default as morrent } from "./images/morrent.svg";
export { default as jobit } from "./images/jobit.svg";
export { default as hipnode } from "./images/hipnode.svg";
export { default as arrow } from "./images/detailProjectArrow.svg";
export { default as stars } from "./images/stars.svg";
export { default as adrian } from "./images/adrian.png";
export { default as test } from "./images/test.jpg";
export { default as test2 } from "./images/test2.jpeg";
